#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by fm-brief.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/fm-brief.sh"
TMP_ROOT=$(fm_test_tmproot fm-ask-user-authority)

test_primary_and_secondmate_instruction_generation() {
  local home ship charter mode
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  for mode in direct-PR no-mistakes; do
    FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" \
      "$BRIEF" "authority-worker-$mode" sample --mode "$mode" >/dev/null 2>&1 \
      || fail "could not generate $mode implementation brief"
    ship="$home/data/authority-worker-$mode/brief.md"
    assert_grep 'If a decision belongs above the implementation worker (product choices, destructive actions),' "$ship" \
      "generated implementation brief does not identify decisions outside worker authority"
    # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
    assert_grep 'append `needs-decision [at=<epoch>]: {summary of options}` and stop. Firstmate will reply with the decision.' "$ship" \
      "generated implementation brief bypasses firstmate decision routing"
    assert_grep 'Never merge a PR.' "$ship" \
      "generated implementation brief gives the worker merge authority"
    assert_grep 'Do not install or invoke no-mistakes, gh-axi, chrome-devtools-axi, or lavish-axi.' "$ship" \
      "generated implementation brief permits removed tooling"
    # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
    assert_grep 'push your branch and open a PR with `gh`' "$ship" \
      "generated implementation brief does not use supported PR tooling"
    assert_grep 'Do NOT run /no-mistakes.' "$ship" \
      "generated implementation brief retained the pipeline requirement"
    assert_no_grep 'no-mistakes axi' "$ship" \
      "generated implementation brief retained pipeline-specific authority instructions"
    assert_no_grep 'the captain, not you, owns the ask-user decisions' "$ship" \
      "generated implementation brief retained conflicting captain-only wording"
  done

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" FM_SECONDMATE_CHARTER='Handle sample work.' \
    "$BRIEF" authority-mate --secondmate --no-projects >/dev/null 2>&1 \
    || fail "could not generate secondmate charter"
  charter="$home/data/authority-mate/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated secondmate charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated secondmate charter duplicated the detailed authority procedure"
  pass "primary workers and secondmates receive the authority rule through generated instructions"
}

test_primary_and_secondmate_instruction_generation
