#!/usr/bin/env bash
# Supervision host behavior: attended dispatch and dialog delivery.
# Shared fixtures and cases keep the same bounds across the serial suites.
# shellcheck source=tests/supervision-host-helpers.sh
. "$(dirname "${BASH_SOURCE[0]}")/supervision-host-helpers.sh"

test_attended_routine_wake_is_handled_on_the_engine_and_stays_off_main
test_attended_captain_outcome_reaches_main_through_branch_outcomes
test_captain_leaving_mid_turn_keeps_its_captain_outcome_for_the_return
test_quiet_record_without_its_daemon_is_a_present_captain
test_attended_main_only_close_passes_straight_to_main
test_off_written_while_parked_passes_the_next_attended_close_to_main
test_main_only_pass_through_leaves_the_successor_watcher_running
test_attended_close_with_unidentified_main_session_passes_to_main
test_close_accepted_away_that_turns_attended_passes_to_main
test_attended_close_that_turns_main_only_before_its_turn_passes_to_main
test_claude_stop_hook_delivers_a_main_only_pass_through
test_acknowledged_host_recovery_settles
test_host_takeover_waits_full_stop_bound
test_host_takeover_accepts_decimal_stop_bound
test_host_takeover_accepts_prefixed_term_receipt
test_host_recovery_after_real_successor_downtime
test_claude_stop_hook_rewakes_a_present_captain_beside_a_quiet_record
test_claude_stop_hook_runs_the_host_without_the_file_and_off_opts_out
test_claude_stop_hook_delivers_a_close_that_turns_main_only_at_its_turn
test_claude_stop_hook_notifies_when_at_turn_downtime_write_fails
test_successor_close_during_main_turn_is_delivered_at_the_next_turn_end
test_next_park_takes_over_the_cycle_a_pass_through_left_for_main
test_a_park_stopped_mid_take_over_leaves_the_take_over_to_the_next_park
test_unrecorded_successor_is_stopped_rather_than_left_for_main
test_primary_without_a_verified_mirror_runs_away_only
test_attended_wake_carries_the_dialog_mirror
test_dialog_bearing_files_are_owner_only
test_undelivered_dialog_is_fed_again_on_the_next_turn
test_attended_wake_with_an_unreadable_mirror_reaches_main
